const destinations = [
  // Domestic (Korea)
  {
    id: 'd1',
    name: '제주도 (Jeju Island)',
    location: 'domestic',
    duration: ['1-3', '4-7'],
    style: ['relaxation', 'nature', 'food'],
    image: 'https://images.unsplash.com/photo-1589370830491-0306385a8553?auto=format&fit=crop&q=80&w=800',
    description: '에메랄드빛 바다와 아름다운 오름, 맛있는 흑돼지와 해산물이 있는 환상의 섬.',
  },
  {
    id: 'd2',
    name: '부산 (Busan)',
    location: 'domestic',
    duration: ['1-3'],
    style: ['city', 'food', 'nightlife'],
    image: 'https://images.unsplash.com/photo-1616421946029-7c30089ffb57?auto=format&fit=crop&q=80&w=800',
    description: '해운대의 화려한 야경과 맛있는 밀면, 돼지국밥! 활기찬 해양 도시.',
  },
  {
    id: 'd3',
    name: '강릉/속초 (Gangneung/Sokcho)',
    location: 'domestic',
    duration: ['1-3'],
    style: ['relaxation', 'food', 'nature'],
    image: 'https://images.unsplash.com/photo-1598006199341-c1e1562b5d49?auto=format&fit=crop&q=80&w=800',
    description: '시원한 동해 바다와 설악산, 그리고 신선한 회와 닭강정.',
  },
  {
    id: 'd4',
    name: '경주 (Gyeongju)',
    location: 'domestic',
    duration: ['1-3', '4-7'],
    style: ['history', 'culture', 'relaxation'],
    image: 'https://images.unsplash.com/photo-1596706037042-45e0d79d854e?auto=format&fit=crop&q=80&w=800',
    description: '천년의 역사가 숨 쉬는 곳. 황리단길의 트렌디함과 고즈넉한 한옥의 조화.',
  },

  // International - Short Flight (< 3 hours)
  {
    id: 'i1',
    name: '오사카, 일본 (Osaka, Japan)',
    location: 'international',
    flight: 'short',
    duration: ['1-3', '4-7'],
    style: ['food', 'city', 'shopping'],
    image: 'https://images.unsplash.com/photo-1590559899731-a382839ceab5?auto=format&fit=crop&q=80&w=800',
    description: '먹다가 망한다는 미식의 도시. 화려한 도톤보리와 유니버셜 스튜디오.',
  },
  {
    id: 'i2',
    name: '후쿠오카, 일본 (Fukuoka, Japan)',
    location: 'international',
    flight: 'short',
    duration: ['1-3'],
    style: ['food', 'relaxation', 'shopping'],
    image: 'https://images.unsplash.com/photo-1522850959516-58f9589ebecd?auto=format&fit=crop&q=80&w=800',
    description: '가깝고 맛있는 도시. 돈코츠 라멘의 본고장과 따뜻한 온천 여행.',
  },
  {
    id: 'i3',
    name: '타이베이, 대만 (Taipei, Taiwan)',
    location: 'international',
    flight: 'short',
    duration: ['1-3', '4-7'],
    style: ['food', 'culture', 'nightlife'],
    image: 'https://images.unsplash.com/photo-1552993873-0aa0cc099049?auto=format&fit=crop&q=80&w=800',
    description: '다채로운 길거리 음식과 지우펀의 야경, 친절한 사람들이 있는 곳.',
  },

  // International - Medium Flight (3-6 hours)
  {
    id: 'i4',
    name: '다낭, 베트남 (Da Nang, Vietnam)',
    location: 'international',
    flight: 'medium',
    duration: ['4-7'],
    style: ['relaxation', 'food', 'family'],
    image: 'https://images.unsplash.com/photo-1583417646487-1950e82c1613?auto=format&fit=crop&q=80&w=800',
    description: '가성비 최고의 휴양지. 아름다운 해변과 저렴하고 맛있는 로컬 푸드.',
  },
  {
    id: 'i5',
    name: '방콕, 태국 (Bangkok, Thailand)',
    location: 'international',
    flight: 'medium',
    duration: ['4-7'],
    style: ['food', 'nightlife', 'shopping', 'culture'],
    image: 'https://images.unsplash.com/photo-1583491470869-d8e788090728?auto=format&fit=crop&q=80&w=800',
    description: '화려한 사원과 끝없는 길거리 음식, 저렴한 마사지와 생동감 넘치는 도시.',
  },
  {
    id: 'i6',
    name: '괌 (Guam, USA)',
    location: 'international',
    flight: 'medium',
    duration: ['4-7'],
    style: ['relaxation', 'shopping', 'family', 'nature'],
    image: 'https://images.unsplash.com/photo-1632788390977-b89e7cb28189?auto=format&fit=crop&q=80&w=800',
    description: '태평양의 에메랄드빛 바다. 쇼핑과 해양 스포츠를 동시에 즐길 수 있는 휴양지.',
  },

  // International - Long Flight (> 6 hours)
  {
    id: 'i7',
    name: '파리, 프랑스 (Paris, France)',
    location: 'international',
    flight: 'long',
    duration: ['8+'],
    style: ['culture', 'history', 'shopping', 'romantic'],
    image: 'https://images.unsplash.com/photo-1502602898657-3e907a5ea571?auto=format&fit=crop&q=80&w=800',
    description: '에펠탑과 루브르 박물관, 낭만적인 센 강변을 거니는 유럽 여행의 로망.',
  },
  {
    id: 'i8',
    name: '하와이, 미국 (Hawaii, USA)',
    location: 'international',
    flight: 'long',
    duration: ['8+', '4-7'],
    style: ['relaxation', 'nature', 'adventure', 'romantic'],
    image: 'https://images.unsplash.com/photo-1542259009477-d625272157b7?auto=format&fit=crop&q=80&w=800',
    description: '지상 낙원. 완벽한 날씨, 아름다운 해변, 그리고 알로하 스피릿.',
  },
  {
    id: 'i9',
    name: '시드니, 호주 (Sydney, Australia)',
    location: 'international',
    flight: 'long',
    duration: ['8+'],
    style: ['city', 'nature', 'relaxation'],
    image: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&q=80&w=800',
    description: '오페라 하우스와 하버 브리지, 푸른 바다가 어우러진 남반구의 매력적인 도시.',
  }
];
